#!/bin/sh

####################################################################################
#
# This file is part of Jolla recovery console
#
# Copyright (C) 2013 Jolla Ltd.
# Contact: Andrea Bernabei <andrea.bernabei@jollamobile.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
####################################################################################

export PATH=/sbin:/bin:/usr/bin:/usr/sbin

echo "Doing mounts... "
mount /dev
mkdir /dev/pts
mount -a
cat /proc/mounts > /etc/mtab

#Run mdev
echo "Running mdev..."
mdev -s
#Set mdev as hotplug manager
echo /bin/mdev > /proc/sys/kernel/hotplug

write() {
        echo -n "$2" > $1
}

write /sys/class/android_usb/android0/enable 0
write /sys/class/android_usb/android0/idVendor 2931
write /sys/class/android_usb/android0/idProduct 0A06
write /sys/class/android_usb/android0/functions rndis,mass_storage
write /sys/class/android_usb/android0/f_rndis/ethaddr 00:01:02:03:04:05
write /sys/class/android_usb/android0/enable 1
write /sys/class/android_usb/android0/iManufacturer Jolla
write /sys/class/android_usb/android0/iProduct Recovery
write /sys/class/android_usb/android0/iSerial 123456789
write /sys/class/android_usb/android0/enable 1

ip link set rndis0 up
ipaddr add 10.42.66.66/29 broadcast 10.42.66.255 dev rndis0 
ipaddr add 192.168.2.15/24 broadcast 192.168.2.255 dev rndis0 label rndis0:0
udhcpd

echo V > /dev/watchdog

echo "Starting telnetd..."
telnetd -l/usr/bin/recovery-menu &

sleep 86400

