#!/bin/sh

##############################################################################
#
# This file is part of Jolla recovery console
#
# Copyright (C) 2013-2015 Jolla Ltd.
# Originally written by Andrea Bernabei
# Contact: Igor Zhbanov <igor.zhbanov@jolla.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
##############################################################################

export PATH=/sbin:/bin:/usr/bin:/usr/sbin

. /usr/bin/recovery-functions.sh

echo "Doing mounts... "
mount /dev
mkdir /dev/pts
mount -a
cat /proc/mounts > /etc/mtab

#Run mdev
echo "Running mdev..."
mdev -s
#Set mdev as hotplug manager
echo /bin/mdev > /proc/sys/kernel/hotplug

write()
{
	echo -n "$2" > $1
}

# Minimize power consumption by lowering display brightness to minimum
write /sys/class/backlight/intel_backlight/brightness 0

write /sys/class/android_usb/android0/enable 0
write /sys/class/android_usb/android0/idVendor 2931
write /sys/class/android_usb/android0/idProduct 0A06
write /sys/class/android_usb/android0/functions rndis,mass_storage
write /sys/class/android_usb/android0/f_rndis/ethaddr 00:01:02:03:04:05
write /sys/class/android_usb/android0/enable 1
write /sys/class/android_usb/android0/iManufacturer Jolla
write /sys/class/android_usb/android0/iProduct Recovery
write /sys/class/android_usb/android0/iSerial $(txeireader --serial)
write /sys/class/android_usb/android0/enable 1

ip link set rndis0 up
ipaddr add 10.42.66.66/29 broadcast 10.42.66.255 dev rndis0
ipaddr add 192.168.2.15/24 broadcast 192.168.2.255 dev rndis0 label rndis0:0
udhcpd

for dev in $(ls -1 -d /sys/class/input/event*); do
	if cat $dev/device/name | grep dollar_cove_power_button; then
		ln -s /dev/input/$(echo $dev | cut -d '/' -f 5) /dev/powerkey
		break
	fi
done

echo V > /dev/watchdog

# On intel platform the framebuffer seems to stay on, so just draw and exit
yamui -t "RECOVERY: Connect USB cable and open telnet connection to address 10.42.66.66" -s 1

# Remove recovery-menu lock if the /var/run is not on tmpfs.
remove_lock

echo "Starting telnetd..."
telnetd -l/usr/bin/recovery-menu &

echo "Starting yamui-screensaverd..."
/usr/bin/yamui-screensaverd &

sleep 86400
